// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void freq_serial (
ap_uint<32> freqStream[32],
ap_uint<32> serialTwoStream[96],
ap_uint<32> serialThreeStream[112],
ap_uint<32> seed,
ap_uint<44> n,
ap_uint<1> offset);
