# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/FYP_160611/FYP/FYP.cache/wt [current_project]
set_property parent.project_path C:/FYP_160611/FYP/FYP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {{c:/Users/s02so/Desktop/Code Generations/IP Folders/xorshift}} [current_project]
add_files C:/FYP_160611/FYP/FYP.srcs/sources_1/bd/block_design1/block_design1.bd
set_property used_in_implementation false [get_files -all c:/FYP_160611/FYP/FYP.srcs/sources_1/bd/block_design1/ip/block_design1_processing_system7_0_0/block_design1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/FYP_160611/FYP/FYP.srcs/sources_1/bd/block_design1/ip/block_design1_rst_processing_system7_0_100M_0/block_design1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FYP_160611/FYP/FYP.srcs/sources_1/bd/block_design1/ip/block_design1_rst_processing_system7_0_100M_0/block_design1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/FYP_160611/FYP/FYP.srcs/sources_1/bd/block_design1/ip/block_design1_rst_processing_system7_0_100M_0/block_design1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FYP_160611/FYP/FYP.srcs/sources_1/bd/block_design1/ip/block_design1_freq_serial_0_0/constraints/freq_serial_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FYP_160611/FYP/FYP.srcs/sources_1/bd/block_design1/ip/block_design1_auto_pc_0/block_design1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/FYP_160611/FYP/FYP.srcs/sources_1/bd/block_design1/block_design1_ooc.xdc]
set_property is_locked true [get_files C:/FYP_160611/FYP/FYP.srcs/sources_1/bd/block_design1/block_design1.bd]

read_verilog -library xil_defaultlib C:/FYP_160611/FYP/FYP.srcs/sources_1/bd/block_design1/hdl/block_design1_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top block_design1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef block_design1_wrapper.dcp

catch { report_utilization -file block_design1_wrapper_utilization_synth.rpt -pb block_design1_wrapper_utilization_synth.pb }
