// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xfreq_serial.h"

extern XFreq_serial_Config XFreq_serial_ConfigTable[];

XFreq_serial_Config *XFreq_serial_LookupConfig(u16 DeviceId) {
	XFreq_serial_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFREQ_SERIAL_NUM_INSTANCES; Index++) {
		if (XFreq_serial_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XFreq_serial_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XFreq_serial_Initialize(XFreq_serial *InstancePtr, u16 DeviceId) {
	XFreq_serial_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XFreq_serial_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XFreq_serial_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

