// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// FREQ_PERIPH_BUS
// 0x000 : Control signals
//         bit 0  - ap_start (Read/Write/COH)
//         bit 1  - ap_done (Read/COR)
//         bit 2  - ap_idle (Read)
//         bit 3  - ap_ready (Read)
//         bit 7  - auto_restart (Read/Write)
//         others - reserved
// 0x004 : Global Interrupt Enable Register
//         bit 0  - Global Interrupt Enable (Read/Write)
//         others - reserved
// 0x008 : IP Interrupt Enable Register (Read/Write)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x00c : IP Interrupt Status Register (Read/TOW)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x600 : Data signal of seed_V
//         bit 31~0 - seed_V[31:0] (Read/Write)
// 0x604 : reserved
// 0x608 : Data signal of n_V
//         bit 31~0 - n_V[31:0] (Read/Write)
// 0x60c : Data signal of n_V
//         bit 11~0 - n_V[43:32] (Read/Write)
//         others   - reserved
// 0x610 : reserved
// 0x614 : Data signal of offset_V
//         bit 0  - offset_V[0] (Read/Write)
//         others - reserved
// 0x618 : reserved
// 0x080 ~
// 0x0ff : Memory 'freqStream_V' (32 * 32b)
//         Word n : bit [31:0] - freqStream_V[n]
// 0x200 ~
// 0x3ff : Memory 'serialTwoStream_V' (96 * 32b)
//         Word n : bit [31:0] - serialTwoStream_V[n]
// 0x400 ~
// 0x5ff : Memory 'serialThreeStream_V' (112 * 32b)
//         Word n : bit [31:0] - serialThreeStream_V[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_AP_CTRL                  0x000
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_GIE                      0x004
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_IER                      0x008
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_ISR                      0x00c
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_SEED_V_DATA              0x600
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_BITS_SEED_V_DATA              32
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_N_V_DATA                 0x608
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_BITS_N_V_DATA                 44
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_OFFSET_V_DATA            0x614
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_BITS_OFFSET_V_DATA            1
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_FREQSTREAM_V_BASE        0x080
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_FREQSTREAM_V_HIGH        0x0ff
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_WIDTH_FREQSTREAM_V            32
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_DEPTH_FREQSTREAM_V            32
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_SERIALTWOSTREAM_V_BASE   0x200
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_SERIALTWOSTREAM_V_HIGH   0x3ff
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_WIDTH_SERIALTWOSTREAM_V       32
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_DEPTH_SERIALTWOSTREAM_V       96
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_SERIALTHREESTREAM_V_BASE 0x400
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_ADDR_SERIALTHREESTREAM_V_HIGH 0x5ff
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_WIDTH_SERIALTHREESTREAM_V     32
#define XFREQ_SERIAL_FREQ_PERIPH_BUS_DEPTH_SERIALTHREESTREAM_V     112

